/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a new User. */
        post: operations["createUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Rename a User. */
        patch: operations["renameUser"];
        trace?: never;
    };
    "/users/{userId}/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Archive a User. Idempotent. */
        post: operations["archiveUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/universes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a new Universe. */
        post: operations["createUniverse"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/universes/{universeId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Rename a Universe. */
        patch: operations["renameUniverse"];
        trace?: never;
    };
    "/universes/{universeId}/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Archive a Universe. Idempotent. */
        post: operations["archiveUniverse"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/universes/{universeId}/creators/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add a Creator to a Universe. Idempotent. */
        post: operations["addUniverseCreator"];
        /** Remove a Creator from a Universe. Rejected if this is the last Creator. */
        delete: operations["removeUniverseCreator"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/universes/{universeId}/campaigns": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a new Campaign under a Universe. */
        post: operations["createCampaign"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/campaigns/{campaignId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Rename a Campaign. */
        patch: operations["renameCampaign"];
        trace?: never;
    };
    "/campaigns/{campaignId}/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Archive a Campaign. Idempotent. */
        post: operations["archiveCampaign"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/campaigns/{campaignId}/gamemasters/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add a Gamemaster to a Campaign. Idempotent. */
        post: operations["addCampaignGamemaster"];
        /** Remove a Gamemaster from a Campaign. Rejected if this is the last Gamemaster. */
        delete: operations["removeCampaignGamemaster"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/campaigns/{campaignId}/configuration": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Replace a Campaign's configuration (an opaque JSON string the backend never parses or validates). */
        put: operations["setCampaignConfiguration"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/campaigns/{campaignId}/configure": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Request configuration of a Campaign. Does not change the Campaign directly — raises a ConfigurationRequested event that timadorus-engine may or may not act on, asynchronously. */
        put: operations["requestCampaignConfiguration"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/universes/{universeId}/entities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a new Entity under a Universe. */
        post: operations["createEntity"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/entities/{entityId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Rename an Entity. */
        patch: operations["renameEntity"];
        trace?: never;
    };
    "/entities/{entityId}/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Archive an Entity. Idempotent. */
        post: operations["archiveEntity"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/campaigns/{campaignId}/characters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a new Character under a Campaign, atomically creating its paired Entity (plan §4.4). The response includes both ids since the Entity was created implicitly and the client has no other way to learn its id. */
        post: operations["createCharacter"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/characters/{characterId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Rename a Character. */
        patch: operations["renameCharacter"];
        trace?: never;
    };
    "/characters/{characterId}/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Archive a Character. Idempotent. */
        post: operations["archiveCharacter"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/characters/{characterId}/player": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Reassign a Character's Player. There is no "unset" — a Character always has exactly one Player. */
        put: operations["setCharacterPlayer"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/characters/{characterId}/info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Replace a Character's info (an opaque JSON string the backend never parses or validates). */
        put: operations["setCharacterInfo"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/characters/{characterId}/action": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Request an action on a Character. Does not change the Character directly — raises an ActionRequested event that timadorus-engine may or may not act on, asynchronously. */
        put: operations["requestCharacterAction"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/universes/{universeId}/objects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a new Object under a Universe. */
        post: operations["createObject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/objects/{objectId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Rename an Object. */
        patch: operations["renameObject"];
        trace?: never;
    };
    "/objects/{objectId}/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Archive an Object. Idempotent. */
        post: operations["archiveObject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rulesets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a new Ruleset. */
        post: operations["createRuleset"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rulesets/{rulesetId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Rename a Ruleset. */
        patch: operations["renameRuleset"];
        trace?: never;
    };
    "/rulesets/{rulesetId}/description": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Replace a Ruleset's description. */
        put: operations["setRulesetDescription"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rulesets/{rulesetId}/references": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Replace a Ruleset's references list. */
        put: operations["setRulesetReferences"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rulesets/{rulesetId}/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Archive a Ruleset. Idempotent. */
        post: operations["archiveRuleset"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CreateObjectRequest: {
            name: string;
        };
        ObjectCreatedResponse: {
            /** Format: uuid */
            id: string;
        };
        CreateRulesetRequest: {
            name: string;
            description?: string;
            references?: string[];
        };
        RulesetCreatedResponse: {
            /** Format: uuid */
            id: string;
        };
        SetRulesetDescriptionRequest: {
            description: string;
        };
        SetRulesetReferencesRequest: {
            references: string[];
        };
        CreateCharacterRequest: {
            name: string;
            /** Format: uuid */
            playerUserId: string;
        };
        CharacterCreatedResponse: {
            /** Format: uuid */
            characterId: string;
            /** Format: uuid */
            entityId: string;
        };
        SetPlayerRequest: {
            /** Format: uuid */
            userId: string;
        };
        SetCharacterInfoRequest: {
            info: string;
        };
        CreateEntityRequest: {
            name: string;
        };
        EntityCreatedResponse: {
            /** Format: uuid */
            id: string;
        };
        CreateCampaignRequest: {
            name: string;
            /** Format: uuid */
            rulesetId: string;
            gamemasterUserIds: string[];
        };
        CampaignCreatedResponse: {
            /** Format: uuid */
            id: string;
        };
        SetCampaignConfigurationRequest: {
            configuration: string;
        };
        CreateUserRequest: {
            name: string;
        };
        UserCreatedResponse: {
            /** Format: uuid */
            id: string;
        };
        CreateUniverseRequest: {
            name: string;
            creatorUserIds: string[];
        };
        RenameRequest: {
            name: string;
        };
        UniverseCreatedResponse: {
            /** Format: uuid */
            id: string;
        };
        /** @description RFC 7807 problem+json error body. */
        Problem: {
            title?: string;
            detail?: string;
            status?: number;
        };
    };
    responses: {
        /** @description Malformed request. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Aggregate or referenced parent/user not found. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Invariant violation (e.g. last creator), archived aggregate, or optimistic concurrency conflict. */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Domain validation failure (e.g. empty name). */
        UnprocessableEntity: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        UniverseId: string;
        UserId: string;
        CampaignId: string;
        EntityId: string;
        CharacterId: string;
        ObjectId: string;
        RulesetId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    createUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUserRequest"];
            };
        };
        responses: {
            /** @description User created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserCreatedResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            422: components["responses"]["UnprocessableEntity"];
        };
    };
    renameUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: components["parameters"]["UserId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RenameRequest"];
            };
        };
        responses: {
            /** @description Renamed. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["UnprocessableEntity"];
        };
    };
    archiveUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: components["parameters"]["UserId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Archived (or already archived). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
        };
    };
    createUniverse: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUniverseRequest"];
            };
        };
        responses: {
            /** @description Universe created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UniverseCreatedResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            422: components["responses"]["UnprocessableEntity"];
        };
    };
    renameUniverse: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                universeId: components["parameters"]["UniverseId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RenameRequest"];
            };
        };
        responses: {
            /** @description Renamed. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["UnprocessableEntity"];
        };
    };
    archiveUniverse: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                universeId: components["parameters"]["UniverseId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Archived (or already archived). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
        };
    };
    addUniverseCreator: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                universeId: components["parameters"]["UniverseId"];
                userId: components["parameters"]["UserId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Added (or already present). */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    removeUniverseCreator: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                universeId: components["parameters"]["UniverseId"];
                userId: components["parameters"]["UserId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Removed. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    createCampaign: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                universeId: components["parameters"]["UniverseId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCampaignRequest"];
            };
        };
        responses: {
            /** @description Campaign created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CampaignCreatedResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["UnprocessableEntity"];
        };
    };
    renameCampaign: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                campaignId: components["parameters"]["CampaignId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RenameRequest"];
            };
        };
        responses: {
            /** @description Renamed. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["UnprocessableEntity"];
        };
    };
    archiveCampaign: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                campaignId: components["parameters"]["CampaignId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Archived (or already archived). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
        };
    };
    addCampaignGamemaster: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                campaignId: components["parameters"]["CampaignId"];
                userId: components["parameters"]["UserId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Added (or already present). */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    removeCampaignGamemaster: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                campaignId: components["parameters"]["CampaignId"];
                userId: components["parameters"]["UserId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Removed. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    setCampaignConfiguration: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                campaignId: components["parameters"]["CampaignId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetCampaignConfigurationRequest"];
            };
        };
        responses: {
            /** @description Updated. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    requestCampaignConfiguration: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                campaignId: components["parameters"]["CampaignId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": Record<string, never>;
            };
        };
        responses: {
            /** @description Configuration requested. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    createEntity: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                universeId: components["parameters"]["UniverseId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateEntityRequest"];
            };
        };
        responses: {
            /** @description Entity created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntityCreatedResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["UnprocessableEntity"];
        };
    };
    renameEntity: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entityId: components["parameters"]["EntityId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RenameRequest"];
            };
        };
        responses: {
            /** @description Renamed. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["UnprocessableEntity"];
        };
    };
    archiveEntity: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entityId: components["parameters"]["EntityId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Archived (or already archived). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
        };
    };
    createCharacter: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                campaignId: components["parameters"]["CampaignId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCharacterRequest"];
            };
        };
        responses: {
            /** @description Character (and its paired Entity) created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CharacterCreatedResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["UnprocessableEntity"];
        };
    };
    renameCharacter: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                characterId: components["parameters"]["CharacterId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RenameRequest"];
            };
        };
        responses: {
            /** @description Renamed. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["UnprocessableEntity"];
        };
    };
    archiveCharacter: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                characterId: components["parameters"]["CharacterId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Archived (or already archived). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
        };
    };
    setCharacterPlayer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                characterId: components["parameters"]["CharacterId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetPlayerRequest"];
            };
        };
        responses: {
            /** @description Reassigned. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["UnprocessableEntity"];
        };
    };
    setCharacterInfo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                characterId: components["parameters"]["CharacterId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetCharacterInfoRequest"];
            };
        };
        responses: {
            /** @description Updated. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    requestCharacterAction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                characterId: components["parameters"]["CharacterId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": Record<string, never>;
            };
        };
        responses: {
            /** @description Action requested. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    createObject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                universeId: components["parameters"]["UniverseId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateObjectRequest"];
            };
        };
        responses: {
            /** @description Object created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ObjectCreatedResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["UnprocessableEntity"];
        };
    };
    renameObject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                objectId: components["parameters"]["ObjectId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RenameRequest"];
            };
        };
        responses: {
            /** @description Renamed. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["UnprocessableEntity"];
        };
    };
    archiveObject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                objectId: components["parameters"]["ObjectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Archived (or already archived). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
        };
    };
    createRuleset: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRulesetRequest"];
            };
        };
        responses: {
            /** @description Ruleset created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RulesetCreatedResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["UnprocessableEntity"];
        };
    };
    renameRuleset: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rulesetId: components["parameters"]["RulesetId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RenameRequest"];
            };
        };
        responses: {
            /** @description Renamed. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["UnprocessableEntity"];
        };
    };
    setRulesetDescription: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rulesetId: components["parameters"]["RulesetId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetRulesetDescriptionRequest"];
            };
        };
        responses: {
            /** @description Updated. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    setRulesetReferences: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rulesetId: components["parameters"]["RulesetId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetRulesetReferencesRequest"];
            };
        };
        responses: {
            /** @description Updated. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    archiveRuleset: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rulesetId: components["parameters"]["RulesetId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Archived (or already archived). */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
        };
    };
}
