/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/users/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a User by id. */
        get: operations["getUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/universes/{universeId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a Universe by id. */
        get: operations["getUniverse"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/universes/{universeId}/creators": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List a Universe's Creators. */
        get: operations["listUniverseCreators"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/universes/{universeId}/campaigns": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List non-archived Campaigns under a Universe. */
        get: operations["listCampaignsByUniverse"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/universes/{universeId}/entities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List non-archived Entities under a Universe, optionally filtered by name. */
        get: operations["listEntitiesByUniverse"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/universes/{universeId}/objects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List non-archived Objects under a Universe, optionally filtered by name. */
        get: operations["listObjectsByUniverse"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/universes/{universeId}/changes/cursor": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the current change cursor for a Universe. */
        get: operations["getUniverseChangesCursor"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/universes/{universeId}/changes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List changes to this Universe and everything inside it, after a given cursor. */
        get: operations["listUniverseChanges"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/campaigns/{campaignId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a Campaign by id. */
        get: operations["getCampaign"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/campaigns/{campaignId}/gamemasters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List a Campaign's Gamemasters. */
        get: operations["listCampaignGamemasters"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/campaigns/{campaignId}/characters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List non-archived Characters under a Campaign. */
        get: operations["listCharactersByCampaign"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/entities/{entityId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get an Entity by id. */
        get: operations["getEntity"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/characters/{characterId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a Character by id. */
        get: operations["getCharacter"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/objects/{objectId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get an Object by id. */
        get: operations["getObject"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rulesets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List non-archived Rulesets. */
        get: operations["listRulesets"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rulesets/{rulesetId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a Ruleset by id. */
        get: operations["getRuleset"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rulesets/{rulesetId}/tables/{tableName}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List every row of a Ruleset's named data table. */
        get: operations["listRulesetTableRows"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rulesets/{rulesetId}/tables/{tableName}/{rowKey}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get one row's data from a Ruleset's named data table. */
        get: operations["getRulesetTableRow"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List non-archived Users. */
        get: operations["listUsers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/universes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List non-archived Universes. */
        get: operations["listUniverses"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Object: {
            /** Format: uuid */
            id: string;
            name: string;
            /** Format: uuid */
            universeId: string;
            isArchived: boolean;
        };
        Character: {
            /** Format: uuid */
            id: string;
            name: string;
            /** Format: uuid */
            campaignId: string;
            /** Format: uuid */
            entityId: string;
            /** Format: uuid */
            playerUserId: string;
            info: string;
            isArchived: boolean;
        };
        Entity: {
            /** Format: uuid */
            id: string;
            name: string;
            /** Format: uuid */
            universeId: string;
            isArchived: boolean;
        };
        Campaign: {
            /** Format: uuid */
            id: string;
            name: string;
            /** Format: uuid */
            universeId: string;
            /** Format: uuid */
            rulesetId: string;
            configuration: string;
            isArchived: boolean;
        };
        Ruleset: {
            /** Format: uuid */
            id: string;
            name: string;
            description: string;
            references: string[];
            isArchived: boolean;
        };
        RulesetTableRow: {
            key: string;
            data: Record<string, never>;
        };
        UniverseChangeCursor: {
            /** Format: int64 */
            globalSeq: number;
        };
        UniverseChange: {
            /** Format: int64 */
            globalSeq: number;
            aggregateType: string;
            /** Format: uuid */
            aggregateId: string;
            eventType: string;
            /** Format: date-time */
            occurredAt: string;
        };
        User: {
            /** Format: uuid */
            id: string;
            name: string;
            isArchived: boolean;
        };
        Universe: {
            /** Format: uuid */
            id: string;
            name: string;
            isArchived: boolean;
        };
        /** @description RFC 7807 problem+json error body. */
        Problem: {
            title?: string;
            detail?: string;
            status?: number;
        };
    };
    responses: {
        /** @description Not found. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        UniverseId: string;
        UserId: string;
        CampaignId: string;
        EntityId: string;
        CharacterId: string;
        ObjectId: string;
        RulesetId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: components["parameters"]["UserId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The User. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    getUniverse: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                universeId: components["parameters"]["UniverseId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The Universe. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Universe"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    listUniverseCreators: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                universeId: components["parameters"]["UniverseId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Creator user ids. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    listCampaignsByUniverse: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                universeId: components["parameters"]["UniverseId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Campaigns. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Campaign"][];
                };
            };
        };
    };
    listEntitiesByUniverse: {
        parameters: {
            query?: {
                /** @description Case-insensitive substring match on name. When present, results are capped at 20 and ordered by name; when absent, behavior is unchanged (full non-archived list). */
                name?: string;
            };
            header?: never;
            path: {
                universeId: components["parameters"]["UniverseId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Entities. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Entity"][];
                };
            };
        };
    };
    listObjectsByUniverse: {
        parameters: {
            query?: {
                /** @description Case-insensitive substring match on name. When present, results are capped at 20 and ordered by name; when absent, behavior is unchanged (full non-archived list). */
                name?: string;
            };
            header?: never;
            path: {
                universeId: components["parameters"]["UniverseId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Objects. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Object"][];
                };
            };
        };
    };
    getUniverseChangesCursor: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                universeId: components["parameters"]["UniverseId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The current cursor. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UniverseChangeCursor"];
                };
            };
        };
    };
    listUniverseChanges: {
        parameters: {
            query: {
                since: number;
            };
            header?: never;
            path: {
                universeId: components["parameters"]["UniverseId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Changes, ordered by globalSeq ascending, capped at 20 per call. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UniverseChange"][];
                };
            };
        };
    };
    getCampaign: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                campaignId: components["parameters"]["CampaignId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The Campaign. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Campaign"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    listCampaignGamemasters: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                campaignId: components["parameters"]["CampaignId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Gamemaster user ids. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    listCharactersByCampaign: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                campaignId: components["parameters"]["CampaignId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Characters. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Character"][];
                };
            };
        };
    };
    getEntity: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entityId: components["parameters"]["EntityId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The Entity. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Entity"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    getCharacter: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                characterId: components["parameters"]["CharacterId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The Character. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Character"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    getObject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                objectId: components["parameters"]["ObjectId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The Object. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Object"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    listRulesets: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Rulesets. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ruleset"][];
                };
            };
        };
    };
    getRuleset: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rulesetId: components["parameters"]["RulesetId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The Ruleset. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ruleset"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    listRulesetTableRows: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rulesetId: components["parameters"]["RulesetId"];
                tableName: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Table rows. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RulesetTableRow"][];
                };
            };
        };
    };
    getRulesetTableRow: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rulesetId: components["parameters"]["RulesetId"];
                tableName: string;
                rowKey: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The row's opaque, table-specific data. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    listUsers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Users. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"][];
                };
            };
        };
    };
    listUniverses: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Universes. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Universe"][];
                };
            };
        };
    };
}
