apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "timadorus-platform.fullname" . }}-command-api
  labels:
    {{- include "timadorus-platform.labels" . | nindent 4 }}
spec:
  {{- include "timadorus-platform.gatewayParentRefs" . | nindent 2 }}
  hostnames:
    - {{ required "commandApi.route.hostname is required" .Values.commandApi.route.hostname | quote }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: {{ include "timadorus-platform.fullname" . }}-command-api
          port: {{ .Values.commandApi.containerPort }}
