apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "timadorus-platform.fullname" . }}-migrate
  labels:
    {{- include "timadorus-platform.labels" . | nindent 4 }}
    app.kubernetes.io/component: migrate
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "0"
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
spec:
  backoffLimit: 2
  template:
    metadata:
      labels:
        {{- include "timadorus-platform.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: migrate
    spec:
      restartPolicy: Never
      containers:
        - name: migrate
          image: "{{ .Values.migration.image.repository }}:{{ .Values.migration.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.migration.image.pullPolicy }}
          args: ["up"]
          env:
            {{- include "timadorus-platform.databaseURLEnv" . | nindent 12 }}
          resources:
            {{- toYaml .Values.migration.resources | nindent 12 }}
