apiVersion: v1
kind: Service
metadata:
  name: {{ include "timadorus-platform.fullname" . }}-realtime
  labels:
    {{- include "timadorus-platform.labels" . | nindent 4 }}
    app.kubernetes.io/component: realtime
spec:
  type: ClusterIP
  selector:
    {{- include "timadorus-platform.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: realtime
  ports:
    - name: http
      port: {{ .Values.realtime.containerPort }}
      targetPort: http
