apiVersion: v1
kind: Service
metadata:
  name: {{ include "timadorus-platform.fullname" . }}-timadorus-engine
  labels:
    {{- include "timadorus-platform.labels" . | nindent 4 }}
    app.kubernetes.io/component: timadorus-engine
spec:
  type: ClusterIP
  selector:
    {{- include "timadorus-platform.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: timadorus-engine
  ports:
    - name: http
      port: {{ .Values.timadorusEngine.containerPort }}
      targetPort: http
