apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "timadorus-platform.fullname" . }}-web
  labels:
    {{- include "timadorus-platform.labels" . | nindent 4 }}
spec:
  {{- include "timadorus-platform.gatewayParentRefs" . | nindent 2 }}
  hostnames:
    - {{ required "web.route.hostname is required" .Values.web.route.hostname | quote }}
    {{- if .Values.gateway.pathRouting.hostname }}
    - {{ .Values.gateway.pathRouting.hostname | quote }}
    {{- end }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: {{ include "timadorus-platform.fullname" . }}-web
          port: {{ .Values.web.containerPort }}
