apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "timadorus-platform.fullname" . }}-web-config
  labels:
    {{- include "timadorus-platform.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
data:
  config.json: |
    {
      "commandApiBaseUrl": {{ required "web.config.commandApiBaseUrl is required" .Values.web.config.commandApiBaseUrl | quote }},
      "queryApiBaseUrl": {{ required "web.config.queryApiBaseUrl is required" .Values.web.config.queryApiBaseUrl | quote }},
      "oidc": {
        "authority": {{ required "web.config.oidc.authority is required" .Values.web.config.oidc.authority | quote }},
        "clientId": {{ required "web.config.oidc.clientId is required" .Values.web.config.oidc.clientId | quote }},
        "redirectUri": {{ required "web.config.oidc.redirectUri is required" .Values.web.config.oidc.redirectUri | quote }},
        "postLogoutRedirectUri": {{ required "web.config.oidc.postLogoutRedirectUri is required" .Values.web.config.oidc.postLogoutRedirectUri | quote }}
      }
    }
